//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeekAssistant.prop.resx.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3MiXsFtm3qVasYa1Zfpu3TCsQiZym2cWmY.
        /// </summary>
        internal static string BTCaddress {
            get {
                return ResourceManager.GetString("BTCaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact the developer and provide the error code to fix this bug. (Click the error title for easy copy).
        /// </summary>
        internal static string ContactDevFix {
            get {
                return ResourceManager.GetString("ContactDevFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Verbose Logging in the settings to help the developer pin down the problem..
        /// </summary>
        internal static string EnableVerboseLogging {
            get {
                return ResourceManager.GetString("EnableVerboseLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geek Assistant is still in development... This feature will probably be available in futrue updates..
        /// </summary>
        internal static string FeatureUnavailable {
            get {
                return ResourceManager.GetString("FeatureUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to properly connect your device and try again...
        /// - Install the correct USB drivers for your device
        /// - Turn on USB Debugging
        /// - Allow this PC to access your device (Pop-up)
        /// - Unlock the lockscreen
        /// - Try another USB cable / port.
        /// </summary>
        internal static string TroubleshootConnection {
            get {
                return ResourceManager.GetString("TroubleshootConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can unlock Samsung devices bootloader &amp; FRP using this method:
        /// ❱ Unlock bootloader: ⚠Your device will be factory reset after this⚠
        /// | (Power off) : Hold volume+ and -  : connect USB cable : (Your device will enter download mode) : Hold power up (Unlock) : Read everything then confirm.
        /// | (Wait for it to power on)
        /// |
        /// ❱ Unlock FRP:
        /// | Unhide &quot;Developer options&quot;:
        ///Settings : About : Software information : (Tap &quot;Build number&quot; 7 times) : (Confirm security unlock if asked)
        /// | OEM Unlock:
        ///Settings :  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnlockBL_Samsung {
            get {
                return ResourceManager.GetString("UnlockBL_Samsung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can unlock older Samsung devices FRP using this method:
        /// ❱ Unlock FRP:
        /// | Unhide &quot;Developer options&quot;:
        ///Settings : About : Software information : (Tap &quot;Build number&quot; 7 times) : (Confirm security unlock if asked)
        /// | OEM Unlock:
        ///Settings : Developer options : (Find and Enable &quot;OEM Unlock&quot;)
        ///
        /// ⚠ Warning: Some devices will factory reset when unlocking for security reasons.
        /// ⚠ Notice: If you don&apos;t see &quot;OEM Unlock&quot; then your device is either unlocked by default, or your manufacturer has hidden the option [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnlockBL_Samsung_old {
            get {
                return ResourceManager.GetString("UnlockBL_Samsung_old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to wait the current process to finish first....
        /// </summary>
        internal static string WaitForCurrentProcess {
            get {
                return ResourceManager.GetString("WaitForCurrentProcess", resourceCulture);
            }
        }
    }
}
