//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prop {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class S : global::System.Configuration.ApplicationSettingsBase {

        private static S defaultInstance = ((S)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new S())));

        public static S Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AppMode_newbie {
            get {
                return ((bool)(this["AppMode_newbie"]));
            }
            set {
                this["AppMode_newbie"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoClearLogs {
            get {
                return ((bool)(this["AutoClearLogs"]));
            }
            set {
                this["AutoClearLogs"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AppMode_dontshow {
            get {
                return ((bool)(this["AppMode_dontshow"]));
            }
            set {
                this["AppMode_dontshow"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AppMode_moderate {
            get {
                return ((bool)(this["AppMode_moderate"]));
            }
            set {
                this["AppMode_moderate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DarkTheme {
            get {
                return ((bool)(this["DarkTheme"]));
            }
            set {
                this["DarkTheme"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DeviceAPILevel {
            get {
                return ((int)(this["DeviceAPILevel"]));
            }
            set {
                this["DeviceAPILevel"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DeviceBatteryLevel {
            get {
                return ((int)(this["DeviceBatteryLevel"]));
            }
            set {
                this["DeviceBatteryLevel"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeviceBootloaderUnlocked {
            get {
                return ((bool)(this["DeviceBootloaderUnlocked"]));
            }
            set {
                this["DeviceBootloaderUnlocked"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeviceBootloaderUnlockSupported {
            get {
                return ((bool)(this["DeviceBootloaderUnlockSupported"]));
            }
            set {
                this["DeviceBootloaderUnlockSupported"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeviceBusyBoxReady {
            get {
                return ((bool)(this["DeviceBusyBoxReady"]));
            }
            set {
                this["DeviceBusyBoxReady"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DeviceCount {
            get {
                return ((int)(this["DeviceCount"]));
            }
            set {
                this["DeviceCount"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeviceCustomRecovery {
            get {
                return ((bool)(this["DeviceCustomRecovery"]));
            }
            set {
                this["DeviceCustomRecovery"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeviceCustomROM {
            get {
                return ((bool)(this["DeviceCustomROM"]));
            }
            set {
                this["DeviceCustomROM"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeviceManufacturer {
            get {
                return ((string)(this["DeviceManufacturer"]));
            }
            set {
                this["DeviceManufacturer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeviceRooted {
            get {
                return ((bool)(this["DeviceRooted"]));
            }
            set {
                this["DeviceRooted"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeviceSerial {
            get {
                return ((string)(this["DeviceSerial"]));
            }
            set {
                this["DeviceSerial"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeviceState {
            get {
                return ((string)(this["DeviceState"]));
            }
            set {
                this["DeviceState"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastProgress {
            get {
                return ((string)(this["LastProgress"]));
            }
            set {
                this["LastProgress"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PerformAnimations {
            get {
                return ((bool)(this["PerformAnimations"]));
            }
            set {
                this["PerformAnimations"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PopupMessages {
            get {
                return ((bool)(this["PopupMessages"]));
            }
            set {
                this["PopupMessages"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowToolTips {
            get {
                return ((bool)(this["ShowToolTips"]));
            }
            set {
                this["ShowToolTips"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ToU_dontShow {
            get {
                return ((bool)(this["ToU_dontShow"]));
            }
            set {
                this["ToU_dontShow"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VerboseLogging {
            get {
                return ((bool)(this["VerboseLogging"]));
            }
            set {
                this["VerboseLogging"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VerboseLoggingPrompt {
            get {
                return ((bool)(this["VerboseLoggingPrompt"]));
            }
            set {
                this["VerboseLoggingPrompt"] = value;
            }
        }
    }
}
