'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources.ces

    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class AndroidVer

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
            MyBase.New
        End Sub

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GeekAssistant.AndroidVer", GetType(AndroidVer).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = Value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized string similar to 1.0.
        '''</summary>
        Friend Shared ReadOnly Property _1() As String
            Get
                Return ResourceManager.GetString("1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to 1.1.
        '''</summary>
        Friend Shared ReadOnly Property _2() As String
            Get
                Return ResourceManager.GetString("2", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Cupcake 1.5.
        '''</summary>
        Friend Shared ReadOnly Property _3() As String
            Get
                Return ResourceManager.GetString("3", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Donut 1.6.
        '''</summary>
        Friend Shared ReadOnly Property _4() As String
            Get
                Return ResourceManager.GetString("4", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Eclair 2.0.
        '''</summary>
        Friend Shared ReadOnly Property _5() As String
            Get
                Return ResourceManager.GetString("5", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Eclair 2.0.
        '''</summary>
        Friend Shared ReadOnly Property _6() As String
            Get
                Return ResourceManager.GetString("6", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Eclair 2.1.
        '''</summary>
        Friend Shared ReadOnly Property _7() As String
            Get
                Return ResourceManager.GetString("7", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Froyo 2.2.
        '''</summary>
        Friend Shared ReadOnly Property _8() As String
            Get
                Return ResourceManager.GetString("8", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Gingerbread 2.3.
        '''</summary>
        Friend Shared ReadOnly Property _9() As String
            Get
                Return ResourceManager.GetString("9", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Gingerbread 2.3.
        '''</summary>
        Friend Shared ReadOnly Property _10() As String
            Get
                Return ResourceManager.GetString("10", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Honeycomb 3.0.
        '''</summary>
        Friend Shared ReadOnly Property _11() As String
            Get
                Return ResourceManager.GetString("11", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Honeycomb 3.1.
        '''</summary>
        Friend Shared ReadOnly Property _12() As String
            Get
                Return ResourceManager.GetString("12", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Honeycomb 3.2.
        '''</summary>
        Friend Shared ReadOnly Property _13() As String
            Get
                Return ResourceManager.GetString("13", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to ICS 4.0.
        '''</summary>
        Friend Shared ReadOnly Property _14() As String
            Get
                Return ResourceManager.GetString("14", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to ICS 4.0.
        '''</summary>
        Friend Shared ReadOnly Property _15() As String
            Get
                Return ResourceManager.GetString("15", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Jelly Bean 4.1.
        '''</summary>
        Friend Shared ReadOnly Property _16() As String
            Get
                Return ResourceManager.GetString("16", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Jelly Bean 4.2.
        '''</summary>
        Friend Shared ReadOnly Property _17() As String
            Get
                Return ResourceManager.GetString("17", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Jelly Bean 4.3.
        '''</summary>
        Friend Shared ReadOnly Property _18() As String
            Get
                Return ResourceManager.GetString("18", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to KitKat 4.4.
        '''</summary>
        Friend Shared ReadOnly Property _19() As String
            Get
                Return ResourceManager.GetString("19", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Lollipop 5.0.
        '''</summary>
        Friend Shared ReadOnly Property _21() As String
            Get
                Return ResourceManager.GetString("21", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Lollipop 5.1.
        '''</summary>
        Friend Shared ReadOnly Property _22() As String
            Get
                Return ResourceManager.GetString("22", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Marshmallow 6.0.
        '''</summary>
        Friend Shared ReadOnly Property _23() As String
            Get
                Return ResourceManager.GetString("23", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Nougat 7.0.
        '''</summary>
        Friend Shared ReadOnly Property _24() As String
            Get
                Return ResourceManager.GetString("24", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Nougat 7.1.
        '''</summary>
        Friend Shared ReadOnly Property _25() As String
            Get
                Return ResourceManager.GetString("25", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Oreo 8.0.
        '''</summary>
        Friend Shared ReadOnly Property _26() As String
            Get
                Return ResourceManager.GetString("26", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Oreo 8.1.
        '''</summary>
        Friend Shared ReadOnly Property _27() As String
            Get
                Return ResourceManager.GetString("27", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Pie 9.x.
        '''</summary>
        Friend Shared ReadOnly Property _28() As String
            Get
                Return ResourceManager.GetString("28", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Android 10.
        '''</summary>
        Friend Shared ReadOnly Property _29() As String
            Get
                Return ResourceManager.GetString("29", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Android 11.x (And Above).
        '''</summary>
        Friend Shared ReadOnly Property _30() As String
            Get
                Return ResourceManager.GetString("30", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
